version: "3"

env:
  IMAGE_TAG:
    sh: ./scripts/ci/load-image-version.sh

includes:
  frontend:
    taskfile: ./Taskfile.Frontend.yml
    dir: .
  dotnet:
    taskfile: ./Taskfile.Dotnet.yml
    dir: .
  certs:
    taskfile: ./Taskfile.Certs.yml
    dir: .
  release:
    taskfile: ./Taskfile.Release.yml
    dir: .
  ci:
    taskfile: ./Taskfile.CI.yml
    dir: .
  docker:
    taskfile: ./Taskfile.Docker.yml
    dir: .

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
