version: "3"

includes:
  frontend:
    taskfile: ./Taskfile.Frontend.yml
    dir: .
  dotnet:
    taskfile: ./Taskfile.Dotnet.yml
    dir: .
  certs:
    taskfile: ./Taskfile.Certs.yml
    dir: .

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
