FROM isuperman/elm-devcontainer-foundation:0.1.10

USER root

RUN apt-get update && apt-get install -y \
    xvfb \
    x11vnc \
    novnc \
    websockify \
    procps \
    gettext-base \
    && rm -rf /var/lib/apt/lists/*

USER container-user
RUN curl -fsSL https://claude.ai/install.sh | bash
