<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Verses.fs" />
    <Compile Include="Game.fs" />
    <Compile Include="BibleFileUploadReport.fs" />
    <Compile Include="AbuseReport.fs" />
    <Compile Include="GeneralBugReport.fs" />
  </ItemGroup>

</Project>
